"""Centralized production limits and runtime policy for SATARK."""

MAX_UPLOAD_SIZE_MB = 50
MAX_UPLOAD_BYTES = MAX_UPLOAD_SIZE_MB * 1024 * 1024
URL_FETCH_TIMEOUT_SECONDS = 12
URL_MAX_BYTES = 1_500_000
URL_MAX_TEXT_CHARS = 30_000
URL_MAX_REDIRECTS = 5
URL_USER_AGENT = "SATARK-Security-Analyzer/3.0"
MAX_HISTORY_ITEMS = 50
MAX_TEXT_INPUT_CHARS = 50_000
MAX_ANALYSES_PER_MINUTE = 5
RADAR_Z_INDEX = 0
APP_CONTENT_Z_INDEX = 1
