[theme]
base = "dark"
primaryColor = "#a9a6ff"
backgroundColor = "#080b12"
secondaryBackgroundColor = "#0e1421"
textColor = "#f2f6ff"
font = "sans serif"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[server]
maxUploadSize = 50
